app_name: render

nested:
  things:
  - one
  - two
  - three

inner:
  path: examples/inner.yaml.tmpl

compressed:
  encoded: "H4sIAEJ93FsAA0vOzy0oSi0uTk1RSM7PK0nNKwEAmEAxaRIAAAA="

embed: "content to be embedded"